# Generated by Django 4.2.2 on 2023-06-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sens_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sens_id', to='measurement.sensor'),
        ),
    ]
