# Generated by Django 4.2.2 on 2023-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_sens_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
