# Generated by Django 4.2.2 on 2023-06-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sens_id',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
